### ISSUE TITLE
you should use emoji

### ISSUE THREAD

**Issue by schavery** [alexluecke/asciify-py#1]
i want to see this but with multibyte characters. ascii is lame

**Comment by alexluecke** [comment]
Fine.

**Comment by alexluecke** [comment]
The commit that actually addressed the issue:

https://github.com/alexluecke/asciify-py/commit/9bd5e596a50d74f8b39853b7929c8a158e4cefe1

**Comment by alexluecke** [comment]
And now im going to have to rename the repo >:|
